"""Mine every combat log for what the logging player actually does, per discipline.

Usage:  python overlay/catalog.py [LOG_DIR] [--out docs/CATALOG.md] [--json overlay/catalog.json]
Reads log files only.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from parser import parse_file  # noqa: E402

DEFAULT_DIR = (
    Path(os.environ.get("USERPROFILE", "~")).expanduser()
    / "OneDrive" / "Documents" / "Star Wars - The Old Republic" / "CombatLogs"
)
NOT_EFFECTS = {
    "Damage", "Heal", "AbilityActivate", "AbilityDeactivate", "TargetSet", "TargetCleared",
    "EnterCombat", "ExitCombat", "Death", "Revived", "AreaEntered", "DisciplineChanged",
    "Taunt", "ModifyThreat",
}
BUCKETS = [
    ("Abilities activated", "abilities"),
    ("Self buffs / procs gained", "self_buffs"),
    ("Stack counters (ModifyCharges)", "stacks"),
    ("Debuffs applied to targets", "debuffs_applied"),
    ("Effects applied to you by others (raid buffs, boss debuffs)", "incoming_effects"),
    ("Healing abilities (by heal events)", "heal_abilities"),
    ("Resource events", "resources"),
]


def mine(log_dir: Path):
    cat = defaultdict(lambda: defaultdict(Counter))  # (player, disc) -> bucket -> Counter
    files_per = Counter()
    for path in sorted(log_dir.glob("combat_*.txt")):
        me = None
        key = None
        seen_keys: set = set()
        for ev in parse_file(path):
            if me is None:
                if ev.source and ev.source.kind == "player":
                    me = ev.source.name
                else:
                    continue
            if ev.type == "DisciplineChanged" and ev.source and ev.source.name == me:
                # re-key on every respec so a mid-session swap lands in the right bucket
                key = (me, f"{ev.extra['class'].name}/{ev.extra['discipline'].name}")
                if key not in seen_keys:
                    seen_keys.add(key)
                    files_per[key] += 1
                continue
            if key is None:
                continue
            c = cat[key]
            src_is_me = ev.source is not None and ev.source.kind == "player" and ev.source.name == me
            tgt_is_me = ev.target is not None and ev.target.kind == "player" and ev.target.name == me
            eff = ev.effect.name if ev.effect else ""
            abil = ev.ability.name if ev.ability else ""
            if src_is_me and ev.type == "Event" and eff == "AbilityActivate":
                c["abilities"][abil] += 1
            elif ev.type == "ApplyEffect" and eff not in NOT_EFFECTS:
                if src_is_me and tgt_is_me:
                    c["self_buffs"][eff] += 1
                elif src_is_me:
                    c["debuffs_applied"][eff] += 1
                elif tgt_is_me:
                    who = ev.source.name if ev.source else "?"
                    c["incoming_effects"][f"{eff}  <- {who}"] += 1
            elif ev.type == "ModifyCharges" and (src_is_me or tgt_is_me):
                c["stacks"][eff] += 1
            elif ev.type in ("Spend", "Restore") and src_is_me:
                c["resources"][f"{ev.type} {eff}"] += 1
            elif src_is_me and ev.type == "ApplyEffect" and eff == "Heal":
                c["heal_abilities"][abil] += 1
    return cat, files_per


def write_md(cat, files_per, out: Path, top: int = 40):
    lines = [
        "# What the logs say you actually use",
        "",
        "Auto-generated by `overlay/catalog.py` from every combat log on this PC. Counts are occurrences across all logs.",
        "Use these exact effect names in `rules.py` triggers.",
        "",
    ]
    for key in sorted(cat.keys(), key=lambda k: -files_per[k]):
        player, disc = key
        c = cat[key]
        lines += [f"## {player} - {disc}  ({files_per[key]} logs)", ""]
        for title, bucket in BUCKETS:
            if not c[bucket]:
                continue
            lines += [f"### {title}", "", "| Name | Count |", "|---|---|"]
            for name, n in c[bucket].most_common(top):
                lines.append(f"| {name or '(unnamed)'} | {n} |")
            lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main():
    root = Path(__file__).resolve().parents[1]
    ap = argparse.ArgumentParser()
    ap.add_argument("log_dir", nargs="?", default=str(DEFAULT_DIR))
    ap.add_argument("--out", default=str(root / "docs" / "CATALOG.md"))
    ap.add_argument("--json", default=str(root / "overlay" / "catalog.json"))
    a = ap.parse_args()
    cat, files_per = mine(Path(a.log_dir))
    write_md(cat, files_per, Path(a.out))
    data = {f"{p} | {d}": {b: dict(cnt) for b, cnt in c.items()} for (p, d), c in cat.items()}
    Path(a.json).write_text(json.dumps(data, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"{sum(files_per.values())} logs, {len(cat)} player/discipline combos -> {a.out}")


if __name__ == "__main__":
    main()
